projects:
  leadsup:
    schemaPath: amplify/backend/api/leadsup/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
      - src/app/API.service.ts
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        amplifyJsLibraryVersion: 6
        maxDepth: 2
